# Generated by Django 4.1.7 on 2023-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shops', '0002_remove_product_item_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ManyToManyField(to='core.item'),
        ),
    ]
