# Generated by Django 4.1.7 on 2023-02-26 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0003_remove_product_item_product_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ven', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
