# Generated by Django 4.1.7 on 2023-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shops', '0004_venders_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='venders',
            name='item',
            field=models.ManyToManyField(to='core.item'),
        ),
    ]
