# Generated by Django 4.1.7 on 2024-09-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('purchase', 'Purchase')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productinteraction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
